//-----------------------------------------------------------------------
// <summary>
// Autogenerated Database Interface Class
// </summary>
// <auto-generated />
//-----------------------------------------------------------------------

#nullable enable

using System;
using System.Globalization;
using System.CodeDom.Compiler;
using Cave.Data;

namespace dbstructs.test
{
	/// <summary>Provides access to table structures for database Default.</summary>
	[GeneratedCode("Cave.Data.DatabaseInterfaceGenerator", null)]
	public static partial class SampleV2
	{
		static IDatabase? database;

		/// <summary>Gets the used database instance.</summary>
		public static IDatabase Database => database ?? throw new InvalidOperationException("Database is not connected!");

		/// <summary>Gets or sets the flags used when accessing table instances.</summary>
		public static TableFlags DefaultTableFlags { get; set; }

		/// <summary>Connects to the Default database.</summary>
		/// <param name="storage">IStorage instance to use.</param>
		/// <param name="createIfNotExists">Create the databaseName if its not already present.</param>
		/// <returns>A new <see cref="IDatabase" /> instance.</returns>
		public static void Connect(IStorage storage, bool createIfNotExists = false)
		{
			database = storage.GetDatabase("Default", createIfNotExists);
		}

		/// <summary>Gets or sets the function used to retrieve tables from the database.</summary>
		public static Func<string, ITable> GetTable { get; set; } = (tableName) => Database.GetTable(tableName, DefaultTableFlags);

		/// <summary>Gets a new <see cref="ITable{TKey, TStruct}"/> (long, DefaultSampleRow) instance for accessing the <c>sample</c> table.</summary>
		public static ITable<long, DefaultSampleRow> Sample => new Table<long, DefaultSampleRow>(GetTable("sample"));
	}
}
